// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_marketing_layout from "./routes/(marketing)/_layout.tsx";
import * as $_marketing_pricing from "./routes/(marketing)/pricing.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $admin_layout from "./routes/admin/_layout.tsx";
import * as $admin_middleware from "./routes/admin/_middleware.ts";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $blog_slug_ from "./routes/blog/[slug].tsx";
import * as $broken_handlers_export from "./routes/broken/handlers-export.ts";
import * as $docs_version_index from "./routes/docs/[[version]]/index.tsx";
import * as $ghost from "./routes/ghost.tsx";
import * as $index from "./routes/index.tsx";
import * as $old_path_ from "./routes/old/[...path].ts";
import * as $Comments from "./islands/Comments.tsx";
import * as $DateProp from "./islands/DateProp.tsx";
import * as $Leaky from "./islands/Leaky.tsx";
import * as $LikeButton from "./islands/LikeButton.tsx";
import * as $widgets_Clock from "./islands/widgets/Clock.tsx";
import * as $_marketing_islands_PlanToggle from "./routes/(marketing)/(_islands)/PlanToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/(marketing)/_layout.tsx": $_marketing_layout,
    "./routes/(marketing)/pricing.tsx": $_marketing_pricing,
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/admin/_layout.tsx": $admin_layout,
    "./routes/admin/_middleware.ts": $admin_middleware,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/api/joke.ts": $api_joke,
    "./routes/blog/[slug].tsx": $blog_slug_,
    "./routes/broken/handlers-export.ts": $broken_handlers_export,
    "./routes/docs/[[version]]/index.tsx": $docs_version_index,
    "./routes/ghost.tsx": $ghost,
    "./routes/index.tsx": $index,
    "./routes/old/[...path].ts": $old_path_,
  },
  islands: {
    "./islands/Comments.tsx": $Comments,
    "./islands/DateProp.tsx": $DateProp,
    "./islands/Leaky.tsx": $Leaky,
    "./islands/LikeButton.tsx": $LikeButton,
    "./islands/widgets/Clock.tsx": $widgets_Clock,
    "./routes/(marketing)/(_islands)/PlanToggle.tsx":
      $_marketing_islands_PlanToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
