// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $perfumelanding from "./routes/perfumelanding.tsx";
import * as $PerfumeFilter from "./islands/PerfumeFilter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/perfumelanding.tsx": $perfumelanding,
  },
  islands: {
    "./islands/PerfumeFilter.tsx": $PerfumeFilter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
