// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $joyeriahome from "./routes/joyeriahome.tsx";
import * as $PriceCalculator from "./islands/PriceCalculator.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/joyeriahome.tsx": $joyeriahome,
  },
  islands: {
    "./islands/PriceCalculator.tsx": $PriceCalculator,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
